version: "3.7"
services:
  app:
    build: docker/.
    container_name: app
    command: make run
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    expose:
      - 8080
    tty: true
    restart: always
    networks:
      - internal
  postgres:
    image: postgres:13.3
    container_name: brands_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    networks:
      - internal
#    <<: *services_defaults

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8081:8080"
    expose:
      - 8081
    environment:
      - SWAGGER_JSON=/docs/swagger.yaml
    volumes:
      - ./docs:/docs
    restart: always
  #    networks:
  #      - internal
  #
  prometheus:
    image: prom/prometheus:latest
    container_name: brands_prometheus
    ports:
      - "9090:9090"  # Порт для доступа к Prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - internal

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: brands_jaeger
    ports:
      - "6831:6831/udp"  # Порт для получения трассировок (UDP), обычно для отправки пакетов span в Jaeger.
      - "6832:6832/udp"  # Дополнительный порт для получения трассировок (UDP).
      - "5778:5778"      # Порт для конфигурации и HTTP-запросов от агентов Jaeger.
      - "16686:16686"    # Jaeger UI, доступен по адресу localhost:16686.
      - "4317:4317"      # Порт OTLP gRPC, используется для получения данных трассировок в формате OpenTelemetry.
      - "4318:4318"      # Порт OTLP HTTP, поддерживает данные трассировок и метрик в формате OpenTelemetry.
      - "14250:14250"    # Порт для gRPC подключения к Collector Jaeger.
      - "14268:14268"    # HTTP порт для отправки данных трассировок в Collector Jaeger.
      - "14269:14269"    # Порт для получения данных метрик Collector Jaeger.
      - "9411:9411"      # Порт Zipkin совместимости, используется для отправки трассировок в формате Zipkin.
    restart: unless-stopped
    networks:
      - internal

networks:
  nginx_default:
    external: true
  internal:
    name: itemcloud-brand-local
    driver: bridge

volumes:
  postgres-dev:
  prometheus_data: