name: itemcloud-brands-${REFNAME:-local}

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1024k"
    max-file: "10"

x-services-defaults: &services_defaults
  restart: always
  networks:
    - internal
  logging: *default-logging

services:
  app:
    build: docker/.
    container_name: itemCloudBrandsBackend
    command: make run
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    expose:
      - 8080
    tty: true
    environment:
      REFNAME: "${REFNAME:-local}"

  postgres:
    image: postgres:13.3
    container_name: itemCloudBrandsPostgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-brands}"
      POSTGRES_USER: "${POSTGRES_USER:-brands}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-pgpwdbrands}"
    ports:
      - "5432:5432"
    networks:
      - internal
    <<: *services_defaults

networks:
  nginx_default:
    external: true
  internal:
    name: itemcloud-brands-${REFNAME:-local}
