name: itemcloud-brand-${REFNAME:-local}

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1024k"
    max-file: "10"

x-services-defaults: &services_defaults
  restart: always
  env_file: .env
  networks:
    - internal
  logging: *default-logging

version: "3.9"
services:
  app:
    build: docker/.
    container_name: itemCloudBrandsBackend
    command: make run
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - internal
    tty: true
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "brands"
      POSTGRES_USER: "brands"
      POSTGRES_PASSWORD: "pgpwdbrands"
    ports:
      - "5432:5432"
    networks:
      - internal
    <<: *services_defaults
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api/v1/openapi.yaml
    volumes:
      - ./internal/api/v1:/api/v1
    restart: always
networks:
  nginx_default:
    external: true
  internal:
    name: itemcloud-brand-${REFNAME:-local}
