global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app_metrics'
    static_configs:
      - targets: [ 'app:2112' ]
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'jaeger_metrics'
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8099' ]